name: social_media_app  # Nombre de tu proyecto

description: "A new Flutter project."  # Descripción corta de tu proyecto

# La siguiente línea evita que el paquete sea accidentalmente publicado en pub.dev usando `flutter pub publish`.
# Este es el comportamiento recomendado para paquetes privados.
publish_to: 'none'  # Elimina esta línea si deseas publicar el paquete en pub.dev

# Aquí defines la versión y el número de compilación de tu aplicación.
# Un número de versión se compone de tres números separados por puntos, como 1.2.43,
# seguido de un número de compilación opcional separado por un +.
# El número de versión y el número de compilación pueden ser sobrescritos en el comando `flutter build`,
# especificando `--build-name` y `--build-number`, respectivamente.
# En Android, el número de versión se usa como `versionName` y el número de compilación como `versionCode`.
# En iOS, el número de versión se usa como `CFBundleShortVersionString` y el número de compilación como `CFBundleVersion`.
version: 1.0.0+1  # Versión inicial de la app

environment:
  sdk: ^3.5.3  # Versión del SDK de Dart que usas para este proyecto

# Las dependencias especifican los paquetes adicionales que tu proyecto necesita para funcionar.
# Para actualizar automáticamente las dependencias a la última versión, puedes usar el comando `flutter pub upgrade --major-versions`.
# Alternativamente, las dependencias pueden actualizarse manualmente cambiando los números de versión abajo.
dependencies:
  flutter:
    sdk: flutter  # Flutter SDK necesario para la creación de la aplicación

  # La siguiente línea agrega la fuente de iconos de Cupertino a tu aplicación.
  # Úsalo con la clase `CupertinoIcons` para los iconos de estilo iOS.
  cupertino_icons: ^1.0.8  # Paquete de iconos de Cupertino para aplicaciones iOS
  
  # Dependencias de Firebase para la integración en tu proyecto Flutter.
  # Esto te permitirá trabajar con Firebase en tu app.
  firebase_core: ^3.8.0  # Paquete básico de Firebase para inicializar la conexión con Firebase
  firebase_auth: ^5.3.3  # Paquete para autenticación con Firebase (registro, inicio de sesión, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter  # Dependencia para pruebas en Flutter

  # El paquete "flutter_lints" contiene un conjunto recomendado de lints para fomentar buenas prácticas de codificación.
  # Este conjunto de lints se activa en el archivo `analysis_options.yaml`, ubicado en la raíz de tu paquete.
  # Consulta ese archivo para obtener información sobre cómo desactivar reglas específicas y activar otras.
  flutter_lints: ^4.0.0  # Lints recomendados para ayudar en las buenas prácticas de desarrollo

# Información sobre la parte genérica de Dart en este archivo: 
# https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica para paquetes de Flutter.
flutter:
  # La siguiente línea asegura que la fuente de Material Icons esté incluida en tu aplicación.
  # Esto te permitirá usar los iconos en la clase `MaterialIcons` de Flutter.
  uses-material-design: true  # Asegura que el diseño de Material esté habilitado en tu app

  # Si deseas agregar activos (como imágenes) a tu aplicación, agrega una sección de "assets", como esta:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # Un activo de imagen puede referirse a uno o más "variantes" específicas de resolución. Más detalles en:
  # https://flutter.dev/docs/development/ui/assets-and-images
  #
  # Para más detalles sobre cómo agregar activos desde dependencias de paquetes, consulta:
  # https://flutter.dev/docs/development/packages-and-plugins/using-packages

  # Si deseas agregar fuentes personalizadas a tu aplicación, agrega una sección de "fonts" aquí,
  # dentro de esta sección "flutter". Cada entrada en esta lista debe tener una clave "family" con el nombre de la familia de la fuente,
  # y una clave "fonts" con una lista que dé el archivo de la fuente y otros descriptores si es necesario.
  # Ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para más detalles sobre fuentes desde dependencias de paquetes, consulta:
  # https://flutter.dev/docs/cookbook/design/fonts
